defaults: &defaults
   working_directory: ~/src
   docker:
     - image: vignesh123456/maven-docker
 
version: 2

jobs:

  build:
    <<: *defaults
    
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m   
#    branches:
#      ignore:
 #       - /branch1

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: spring-framework-petclinic-{{ checksum "pom.xml" }}
            
 #     - run:
 #         name: Build & Testing
 #         command: |
 #           mvn package 
            
            
#      - run:
#          name: Install dependencies
#          command: |
#            yum install python -y
#            curl -O https://bootstrap.pypa.io/get-pip.py
#            python get-pip.py
#            pip install awscli==1.11.76
  #    - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build testHTMLproject -t html-server-image:v1
    
      - run:
          name: Run docker image
          command: |
            docker run -d -p 80:80 --name htmlContainer html-server-image:v1

            
      - run:
          name: Check the images present
          command: |
            docker ps
      - run:
          name: Create directory to store result
          command: |
            mkdir test-reports
      
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true

      - run:
          name: Dependency check
          command: |
            mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: Integration testing
          command: |
            mvn clean integration-test
      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/testng/results/
            find . -type f -regex "./test-output/emailable-report.html" -exec cp {} ~/testng/results/ \;
          when: always
      - store_test_results:
          path: ~/testng/results/
      - store_artifacts:
          path: ~/testng/results/
      - store_artifacts:
          path:  testng/results/                             
   #   - run:
   #       name: Build application Docker image
   #       command: |
   #         docker build -t app . 
      
 #     - run: mvn install -DskipTests=true
   #   - save_cache:
   #       paths:
   #         - ~/.m2
   #       key: spring-framework-petclinic-{{ checksum "pom.xml" }}
          
      - store_artifacts:
          path: /root/src/target/petclinic.war
          
      - run:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              CLUSTER='test-app'
              FAMILY='test-app'
              DOCKER_IMAGE='test-app'
              TASK='test-app'
              SERVICE='app-service'
              # Login to AWS
              aws configure set region $AWS_REGION
              pwd="$(aws ecr get-login --region us-east-1 | awk '{print $6}')"
              docker login -u AWS --password "$pwd" $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
              docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              # Create task for docker deploy
              task_template='[
                {
                  "name": "%s",
                  "image": "%s.dkr.ecr.%s.amazonaws.com/%s:%s",
                  "essential": true,
                  "cpu": 128,
                  "memoryReservation": 500,
                  "portMappings": [
                    {
                      "containerPort": 80,
                      "hostPort": 80
                    }
                  ],
                  "environment" : [
                      { "name" : "NODE_ENV", "value" : "production" }
                  ]
                }
              ]'
              echo "$task_template"
              task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $AWS_REGION $TASK $CIRCLE_SHA1)
              # Register task definition
              json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")
              OLD_TASK_ID=$(aws ecs list-tasks --cluster "$CLUSTER" --desired-status RUNNING --family "$FAMILY" | egrep "task/" | sed -E "s/.*task\/(.*)\"/\1/")
              # Grab revision # using regular bash and grep
              revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')
              # Deploy revision 
              aws ecs stop-task --cluster "$CLUSTER" --task "${OLD_TASK_ID}"
              sleep 10
              aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
              return 0
              
            fi
